theme: jekyll-theme-cayman
title: "Interactive PatchMatch-Based Image Completion"
description: 
  "CS 766: Computer Vision, Spring 2018<br><br>Wen-Fu Lee (wlee256@wisc.edu)<br>Yuan-Ting Hsieh (yhsieh28@wisc.edu)<br>Zubeyr Furkan Eryilmaz (eryilmaz@wisc.edu)"
