theme: jekyll-theme-dinky
title: "CS 766<br>Computer Vision"
description: 
  "Spring 2018<br><br>Wen-Fu Lee<br>(wlee256@wisc.edu)<br>Yuan-Ting Hsieh<br>(yhsieh28@wisc.edu)<br>Zubeyr Furkan Eryilmaz<br>(eryilmaz@wisc.edu)"
